---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: perfscale-demo-app
  namespace: perfscale-demo-app
spec:
  selector:
    app: perfscale-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: perfscale-demo-app
    spec:
      containers:
        - name: perfscale-demo-app
          image: quay.io/rhcloudperfscale/perfscale-demo-app:latest
          env:
            - name: POSTGRESQL_HOST
              value: postgresql.perfscale-demo-app.svc
            - name: POSTGRESQL_PORT
              value: 5432
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: perfscale-demo-service
  namespace: perfscale-demo-app
spec:
  selector:
    app: perfscale-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: perfscale-demo-route
  namespace: perfscale-demo-app
spec:
  path: /
  to:
    kind: Service
    name: perfscale-demo-service
  port:
    targetPort: 5000
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql
  namespace: perfscale-demo-app
data:
  database-name: ZGI=
  database-password: cGFzcw==
  database-user: dXNlcg==
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: perfscale-demo-app
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: perfscale-demo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgresql
  namespace: perfscale-demo-app
spec:
  replicas: 1
  selector:
    name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      containers:
        - name: postgresql
          image: 'quay.io/centos7/postgresql-13-centos7'
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresql-data
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql
