---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: perfscale-demo-app
  namespace: perfscale-demo-app
spec:
  selector:
    app: perfscale-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: perfscale-demo-app
    spec:
      containers:
        - name: perfscale-demo-app
          image: quay.io/rhcloudperfscale/perfscale-demo-app:latest
          ports:
            - containerPort: 5000
